### ISSUE TITLE
Sample project does not compile with the last version

### ISSUE THREAD

**Issue by lmouline** [datathings/java2typescript#9]
When I try to compile the sample project using the version 97, I get the following error:

```
[ERROR] Failed to execute goal com.datathings:j2ts-mavenplugin:97:java2ts (transpile) on project j2ts-sample: Execution transpile of goal com.datathings:j2ts-mavenplugin:97:java2ts failed: Unable to make field private static final jdk.internal.misc.Unsafe jdk.internal.misc.Unsafe.theUnsafe accessible: module java.base does not "opens jdk.internal.misc" to unnamed module @70721c12 -> [Help 1]
```

I also get the following warning:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.util.ref.DebugReflectionUtil (file:/Users/ludovicmouline/.m2/repository/org/jetbrains/kotlin/kotlin-compiler/1.1.3/kotlin-compiler-1.1.3.jar) to field java.util.concurrent.atomic.AtomicLongFieldUpdater$CASUpdater.U
WARNING: Please consider reporting this to the maintainers of com.intellij.util.ref.DebugReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Using the full debug mode, I get:

```
[ERROR] Failed to execute goal com.datathings:j2ts-mavenplugin:97:java2ts (transpile) on project j2ts-sample: Execution transpile of goal com.datathings:j2ts-mavenplugin:97:java2ts failed: Unable to make field private static final jdk.internal.misc.Unsafe jdk.internal.misc.Unsafe.theUnsafe accessible: module java.base does not "opens jdk.internal.misc" to unnamed module @3c0e00a8 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.datathings:j2ts-mavenplugin:97:java2ts (transpile) on project j2ts-sample: Execution transpile of goal com.datathings:j2ts-mavenplugin:97:java2ts failed: Unable to make field private static final jdk.internal.misc.Unsafe jdk.internal.misc.Unsafe.theUnsafe accessible: module java.base does not "opens jdk.internal.misc" to unnamed module @3c0e00a8
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution transpile of goal com.datathings:j2ts-mavenplugin:97:java2ts failed: Unable to make field private static final jdk.internal.misc.Unsafe jdk.internal.misc.Unsafe.theUnsafe accessible: module java.base does not "opens jdk.internal.misc" to unnamed module @3c0e00a8
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private static final jdk.internal.misc.Unsafe jdk.internal.misc.Unsafe.theUnsafe accessible: module java.base does not "opens jdk.internal.misc" to unnamed module @3c0e00a8
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:337)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:281)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:176)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:170)
	at com.intellij.util.ref.DebugReflectionUtil.getAllFields(DebugReflectionUtil.java:67)
	at com.intellij.util.ref.DebugReflectionUtil.queueStronglyReferencedValues(DebugReflectionUtil.java:147)
	at com.intellij.util.ref.DebugReflectionUtil.walkObjects(DebugReflectionUtil.java:137)
	at com.intellij.util.CachedValueLeakChecker.findReferencedPsi(CachedValueLeakChecker.java:69)
	at com.intellij.util.CachedValueLeakChecker.checkProvider(CachedValueLeakChecker.java:51)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:57)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:140)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:127)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getFields(ClassInnerStuffCache.java:59)
	at com.intellij.psi.impl.source.PsiClassImpl.getFields(PsiClassImpl.java:291)
	at java2typescript.translators.ClassTranslator.printClassMembers(ClassTranslator.java:105)
	at java2typescript.translators.ClassTranslator.translate(ClassTranslator.java:68)
	at java2typescript.SourceTranslator$1.visitElement(SourceTranslator.java:138)
	at com.intellij.psi.impl.source.PsiClassImpl.accept(PsiClassImpl.java:472)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:857)
	at java2typescript.SourceTranslator.visit(SourceTranslator.java:131)
	at java2typescript.SourceTranslator.visit(SourceTranslator.java:116)
	at java2typescript.SourceTranslator.process(SourceTranslator.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
	at java2typescript.SourceTranslator.process(SourceTranslator.java:92)
	at java2typescript.mavenplugin.Java2TSPlugin.execute(Java2TSPlugin.java:124)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
```

(I didn't dig deeper to understand this bug and to try to find a fix.)

**Comment by dukeboard** [comment]
Hi ludovic,

This error is certainly due to the usage of Java 9 or above which is not supported yet. Could you please try with a JDK 8 to confirm this? Best regards

**Comment by lmouline** [comment]
Working perfectly, thanks ^^"
